volumes:
  pg_data:
  static:
  image_data:

services:
  db:
    image: postgres:16
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
  backend:
    image: skevni/foodgram_backend
    env_file: .env
    volumes:
      - image_data:/var/www/foodgram/media
      - static:/backend_static/
    depends_on:
      - db
    restart: unless-stopped
  frontend:
    env_file: .env
    image: skevni/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
    restart: unless-stopped
  gateway:
    image: skevni/foodgram_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      - image_data:/var/www/foodgram/media
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
